### ISSUE TITLE
How to best integrate with Redux?

### ISSUE THREAD

**Issue by crazyfrozenpenguin** [ghengeveld/react-isomorphic-form#1]
This is a great lib that simplifies Isomorphic form posting.

I have an app that needs to degrade to Isomorphic rendering when JS is not available (or disabled) in the client side. I've used the lib with success and I can post without any issue.

The question is, is there a way to prevent posting when JS is available on the client side?
Basically, if JS is available I don't want to do the post. I just want it to call something like onSubmit so that I can trigger a Redux action/reducer that will then submit the data through websocket to the server.

I know I could create two components and render the appropriate one, but that will create similar component/JSX/HTML duplication.

What would be the best way to achieve this using your lib? Thanks.

**Comment by ghengeveld** [comment]
You can use the `beforeSubmit` prop on Form to intercept form submission. It takes a function, which will be invoked with the form's data when the form is submitted. Return `false` from `beforeSubmit` to prevent the actual POST. Alternatively you can modify the form data and return that. See https://github.com/ghengeveld/react-isomorphic-form/blob/7f1ad931b61ce708f5b4ea091adc4a785b54f40d/src/Form.js#L64-L67

```js
<Form beforeSubmit={onSubmit}>...</Form>

...

function onSubmit(formData) {
  // do stuff with form data, e.g. dispatch an action.
  return false
}
```

**Comment by crazyfrozenpenguin** [comment]
Awesome, thank you!
